import { describe, it } from 'node:test'
import assert from 'node:assert/strict'

import { closingReferences, FAILURE, main } from '../../../tools/github/check-linked-issue.ts'

const run = (env: Record<string, string>) => {
	const out: string[] = []
	const code = main({ env, log: (line) => out.push(line) })
	return { code, out }
}

describe('check linked issue', () => {
	it('finds closing keywords in any case and tense', () => {
		assert.deepEqual(closingReferences('Closes #1\nfixed   #22 and RESOLVES #3'), ['Closes #1', 'fixed   #22', 'RESOLVES #3'])
		assert.deepEqual(closingReferences('See #1, related to #2'), [])
	})

	it('exempts each dependency bot', () => {
		for (const actor of ['renovate[bot]', 'dependabot[bot]', 'github-actions[bot]']) {
			const { code, out } = run({ PR_BODY: '', PR_ACTOR: actor, PR_HEAD_REF: 'x' })
			assert.equal(code, 0)
			assert.deepEqual(out, [`::notice::${actor} is a dependency bot — no linked issue required.`])
		}
	})

	it('exempts the generated translation pull request by branch and body', () => {
		const body = 'Generated by `.github/workflows/i18n-translate.yml`'
		const { code, out } = run({ PR_BODY: body, PR_ACTOR: 'someone', PR_HEAD_REF: 'chore/fr-CA-translations' })
		assert.equal(code, 0)
		assert.deepEqual(out, ['::notice::This is the generated French UI strings PR — no linked issue required.'])
	})

	it('does not exempt the translation branch without the generated body', () => {
		assert.equal(run({ PR_BODY: 'hand written', PR_ACTOR: 'someone', PR_HEAD_REF: 'chore/fr-CA-translations' }).code, 1)
		assert.equal(run({ PR_BODY: 'Generated by `.github/workflows/i18n-translate.yml`', PR_ACTOR: 'someone', PR_HEAD_REF: 'other' }).code, 1)
	})

	it('passes a body that closes issues and notes each link', () => {
		const { code, out } = run({ PR_BODY: 'Closes #5\nFixes #6', PR_ACTOR: 'a', PR_HEAD_REF: 'b' })
		assert.equal(code, 0)
		assert.deepEqual(out, ['::notice::Linked: Closes #5', '::notice::Linked: Fixes #6'])
	})

	it('fails a body that closes nothing with the instructions', () => {
		const { code, out } = run({ PR_BODY: 'Related to #5', PR_ACTOR: 'a', PR_HEAD_REF: 'b' })
		assert.equal(code, 1)
		assert.deepEqual(out, FAILURE)
		assert.equal(out[0], '::error::This pull request does not close an issue.')
	})
})
