// Where the specification lives (ADR-0183). Every tool that reads or writes it
// imports these, so a move is one edit here. Shell hooks and workflows cannot
// import a module; tests/js/spec/spec-paths.test.ts ties them to these values.

export const SPEC_ROOT = '.spec'

/** Generated by tools/spec/generate-spec-index.ts. */
export const SPEC_INDEX = '.spec/README.md'

/** One directory per area: `<area>/<area>.feature` and its README.md. */
export const FEATURES = '.spec/features'

export const DECISIONS = '.spec/decisions'

/**
 * Where decisions lived before ADR-0183. Read only by `adr-numbers.ts --next`,
 * so a remote branch not yet rebased past the move still has its numbers
 * counted. Remove once no remote branch carries it.
 */
export const LEGACY_DECISIONS = 'docs/decisions'

export const LESSONS = '.spec/lessons'

/** New process, tooling, and agent-workflow rules: `CONV-NNN-*.md` (ADR-0192). */
export const CONVENTIONS = '.spec/conventions'

/**
 * The MADR shape every new ADR copies. Its presence on a pull request's base
 * is what puts ADR immutability in force (ADR-0192).
 */
export const ADR_TEMPLATE = '.spec/decisions/TEMPLATE.md'

/** Generated by tools/spec/generate-traceability.ts: the human matrix, one row per claim. */
export const TRACEABILITY = '.spec/traceability.md'

/** Generated by tools/spec/generate-traceability.ts: every claim, constraint, decision, and lesson as data (ADR-0193). */
export const CLAIMS = '.spec/claims.json'

/** The JSON Schema `CLAIMS` conforms to; the generator validates against it. */
export const CLAIMS_SCHEMA = '.spec/claims.schema.json'

// The pages that carry normative constraints. A page not listed here is
// narrative: it describes, it does not require.
export const CONSTRAINT_PAGES = [
	'.spec/system-overview.md',
	'.spec/data-and-persistence.md',
	'.spec/interfaces-and-data-flow.md',
	'.spec/infrastructure-and-operations.md',
	'.spec/testing-and-quality.md',
]

/** Where Reqnroll step definitions live: every claim not tagged @ui. */
export const REQNROLL_STEPS = 'tests/HpacSafety.Acceptance.Tests'

/** Where playwright-bdd step definitions live: every claim tagged @ui. */
export const PLAYWRIGHT_STEPS = 'tests/e2e/steps'
