// Where the specification lives (ADR-0183). Every tool that reads or writes it
// imports these, so a move is one edit here. Shell hooks and workflows cannot
// import a module; tests/js/spec/spec-paths.test.ts ties them to these values.

export const SPEC_ROOT = '.spec'

/** Generated by tools/spec/generate-spec-index.ts. */
export const SPEC_INDEX = '.spec/README.md'

/** One directory per area: `<area>/<area>.feature` and its README.md. */
export const FEATURES = '.spec/features'

export const DECISIONS = '.spec/decisions'

/**
 * Where decisions lived before ADR-0183. Read only by `adr-numbers.ts --next`,
 * so a remote branch not yet rebased past the move still has its numbers
 * counted. Remove once no remote branch carries it.
 */
export const LEGACY_DECISIONS = 'docs/decisions'

export const LESSONS = '.spec/lessons'

/** Generated by tools/spec/generate-traceability.ts. */
export const TRACEABILITY = '.spec/traceability.md'

// The pages that carry normative constraints. A page not listed here is
// narrative: it describes, it does not require.
export const CONSTRAINT_PAGES = [
	'.spec/system-overview.md',
	'.spec/data-and-persistence.md',
	'.spec/interfaces-and-data-flow.md',
	'.spec/infrastructure-and-operations.md',
	'.spec/testing-and-quality.md',
]

/** Generated by tools/spec/generate-bindings.ts: every claim's step-definition files (ADR-0184). */
export const BINDINGS = '.spec/bindings.md'

/** Where Reqnroll step definitions live: every claim not tagged @ui. */
export const REQNROLL_STEPS = 'tests/HpacSafety.Acceptance.Tests'

/** Where playwright-bdd step definitions live: every claim tagged @ui. */
export const PLAYWRIGHT_STEPS = 'tests/e2e/steps'
