#!/usr/bin/env node
// A pull-request body closes an issue.
//
// Nothing in GitHub's settings can force a pull request to close its issue. The
// only mechanism is a closing keyword in the pull request body, which becomes
// the squash commit message because the repository is configured with
// squash_merge_commit_message=PR_BODY. So the body is what gets enforced.
//
// Exempt:
//   * Dependency bots open PRs that legitimately have no issue behind them.
//     The logins are compared literally.
//   * i18n-translate.yml's translation PR is a recurring generated chore, not a
//     backlog item — but TRANSLATION_PR_TOKEN (see ADR-0021) is a personal
//     fine-grained PAT, so `gh pr create` records a real person as PR_ACTOR
//     rather than `github-actions[bot]`, and the bot exemption cannot key off
//     actor. Its head branch name and PR body are both fixed by that workflow,
//     so match on those instead.
//
// Environment: PR_BODY, PR_ACTOR, PR_HEAD_REF. The exit code is the contract.
import { isMain, type Env } from '../lib/actions.ts'

export const BOTS = ['renovate[bot]', 'dependabot[bot]', 'github-actions[bot]']
export const TRANSLATION_BRANCH = 'chore/fr-CA-translations'
export const TRANSLATION_MARKER = 'Generated by `.github/workflows/i18n-translate.yml`'
const CLOSING = /\b(close[sd]?|fixe?[sd]?|resolve[sd]?)[ \t\n\r\f\v]+#[0-9]+/gi

/** Every closing reference in the body, in order. */
export function closingReferences(body: string): string[] {
	return body.match(CLOSING) ?? []
}

/** Why no issue is required, or null. */
export function exemption({ actor, headRef, body }: { actor: string; headRef: string; body: string }): string | null {
	if (BOTS.includes(actor)) return `::notice::${actor} is a dependency bot — no linked issue required.`
	if (headRef === TRANSLATION_BRANCH && body.includes(TRANSLATION_MARKER)) {
		return '::notice::This is the generated French UI strings PR — no linked issue required.'
	}
	return null
}

export const FAILURE = [
	'::error::This pull request does not close an issue.',
	'',
	'Add a closing keyword to the pull request body, on its own line:',
	'',
	'    Closes #123',
	'',
	'GitHub closes the issue on merge only when the keyword is in the body',
	"(or the commit message). 'See #123' and 'Related to #123' do not count.",
	'',
	'If the change genuinely has no issue behind it, open one first —',
	'the backlog is how this project tracks dependencies between changes.',
]

export function main({ env = process.env, log = console.log }: { env?: Env; log?: (line: string) => void } = {}): number {
	const body = env.PR_BODY ?? ''
	const exempt = exemption({ actor: env.PR_ACTOR ?? '', headRef: env.PR_HEAD_REF ?? '', body })
	if (exempt) {
		log(exempt)
		return 0
	}
	const references = closingReferences(body)
	if (references.length > 0) {
		for (const reference of references) log(`::notice::Linked: ${reference}`)
		return 0
	}
	for (const line of FAILURE) log(line)
	return 1
}

if (isMain(import.meta.url)) process.exit(main())
