# Secrets Manager ENTRIES. Never values — with exactly one exception, called
# out below.
#
# A value in a .tfvars file is a value in Terraform state, and state is a file in
# S3 that more people can read than should see an API key. So for every vendor
# secret, Terraform creates the entry, each Lambda function reads its own
# value from Secrets Manager itself, by the ARN Terraform sets in its
# environment (lambda.tf's header comment, SecretArnResolver, #597), and a
# human puts the first value in once:
#
#   aws secretsmanager put-secret-value \
#     --secret-id hpac-safety/gemini-api-key \
#     --secret-string '…'
#
# There is deliberately no `aws_secretsmanager_secret_version` resource for any
# of THESE entries. If you find yourself adding one here, that is the defect —
# every value in `secret_entries` below is a vendor key nobody but a human
# should type. The database connection is NOT one of these entries at all
# (coordinated with #443): the API and the Worker read the RDS-managed
# master-user secret directly, by the ARN lambda.tf passes as a plain,
# non-secret environment variable alongside the equally non-secret host,
# port, and database name, and assemble the connection string themselves at
# cold start. Terraform never reads that secret's value either.
#
# --------------------------------------------------------------------------
# THE ONE EXCEPTION: the CloudFront origin-verify secret
# --------------------------------------------------------------------------
#
# ADR-0159's secret origin header has no vendor and no human-chosen value —
# its only two readers are CloudFront's own origin configuration (cdn.tf) and
# the API, and CloudFront cannot read Secrets Manager at request time, so
# whatever value cdn.tf configures as the literal custom-header value IS the
# value the API must see in Secrets Manager. A human typing a "random" value
# into each side separately is two chances to type it differently — and a
# console edit to reconcile them the next time they drifted would be exactly
# the drift CON-INF-013's fail-on-drift plan is designed to catch, defeating
# the design principle that a release re-plans after it applies and never
# finds a difference (ADR-0158).
#
# So Terraform originates this ONE value with random_password, writes it to
# BOTH places itself (an aws_secretsmanager_secret_version here, and cdn.tf's
# literal custom_header directly from the same resource), and nothing else
# in this directory ever works this way. It is not a vendor credential and
# nobody has to remember it; it exists to prove a request came through this
# distribution and nothing else reads it.
resource "random_password" "cloudfront_origin_secret" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "cloudfront_origin_secret" {
  name        = "${local.name}/cloudfront-origin-secret"
  description = "HpacSafety__Security__OriginVerification__Secret, read by the API itself at cold start via HpacSafety__Security__OriginVerification__SecretArn (#597). Generated by Terraform (the one exception in this file) because both readers — CloudFront's origin config in cdn.tf and the API — must agree on the exact same value and CloudFront cannot read Secrets Manager at request time."

  recovery_window_in_days = 7

  tags = { Name = "${local.name}/cloudfront-origin-secret" }

  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_secretsmanager_secret_version" "cloudfront_origin_secret" {
  secret_id     = aws_secretsmanager_secret.cloudfront_origin_secret.id
  secret_string = random_password.cloudfront_origin_secret.result
}

# --------------------------------------------------------------------------
# Everything else: entry only, value supplied out of band
# --------------------------------------------------------------------------

locals {
  # Description is the whole documentation surface an operator sees in the
  # console, so it says what the value is and who reads it.
  secret_entries = {
    gemini_api_key = {
      name        = "${local.name}/gemini-api-key"
      description = "AiChatClient__ApiKey, read by the API and the Worker themselves at cold start via AiChatClient__ApiKeySecretArn (#597). The paid Gemini key used for the Worker's one summarization model call per attempt (ADR-0104) and for every machine translation, API and Worker alike (ADR-0179). Same value in both environments for now (issue #30)."
    }
  }
}

# The DeepL key's entry is retired (issue #614, ADR-0179): Gemini translates
# with the key above. prevent_destroy on aws_secretsmanager_secret.this refuses
# a plain removal from secret_entries, so the entry is first moved out of the
# for_each resource, then removed with destroy = true. Where the entry was
# never created, both blocks are no-ops. Delete both once every environment has
# applied them.
moved {
  from = aws_secretsmanager_secret.this["deepl_api_key"]
  to   = aws_secretsmanager_secret.retired_deepl_api_key
}

removed {
  from = aws_secretsmanager_secret.retired_deepl_api_key

  lifecycle {
    destroy = true
  }
}

resource "aws_secretsmanager_secret" "this" {
  for_each = local.secret_entries

  name        = each.value.name
  description = each.value.description

  # Long enough to undo a mistaken delete, short enough that the name can be
  # reused within a sprint.
  recovery_window_in_days = 7

  tags = { Name = each.value.name }

  lifecycle {
    # The entry, not its value, is what a plan must never drop: deleting one
    # would break cold start for whichever Lambda function reads it, with no
    # warning until the next invocation. See CON-INF-013.
    prevent_destroy = true
  }
}

# The RDS-managed master password lives in its own secret, created by RDS
# rather than by this file (database.tf's `manage_master_user_password`).
# Both Lambda functions' roles can read it (iam.tf's `rds_master_secret_read`)
# because both assemble the connection string from it at cold start. Its ARN
# is also exposed as an output so an operator can find it without hunting
# through the console.

# --------------------------------------------------------------------------
# The temporary interim-issuer signing key (issue #648, ADR-0172)
# --------------------------------------------------------------------------
#
# Entry only, created only when var.interim_issuer_enabled — staging today,
# never production. Unlike every entry in `secret_entries` above, there is
# deliberately NO prevent_destroy here: this whole feature, this secret
# included, is meant to be deleted in one sweep once a real identity provider
# exists (ADR-0064) — the same reason there is no aws_secretsmanager_secret_version
# resource either. deploy-environment.yml's "Generate the interim issuer
# signing key" step puts the one value — an RSA private key PEM it generates
# itself with openssl, never a human-typed vendor key — only when the entry
# has no AWSCURRENT version yet, and never reads it back.
resource "aws_secretsmanager_secret" "interim_issuer_signing_key" {
  count = var.interim_issuer_enabled ? 1 : 0

  name        = "${local.name}/interim-issuer-signing-key"
  description = "HpacSafety__Authentication__InterimIssuer__SigningKeyPem, read by the API itself at cold start via HpacSafety__Authentication__InterimIssuer__SigningKeySecretArn (#597, ADR-0172). An RSA private key PEM, generated once by deploy-environment.yml if this entry has no AWSCURRENT version yet. TEMPORARY: deleted along with the whole interim-issuer feature once a real identity provider exists (ADR-0064) — deliberately no prevent_destroy, unlike every other entry in this file."

  recovery_window_in_days = 7

  tags = { Name = "${local.name}/interim-issuer-signing-key" }
}
