import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

import { main, prBody, PR_TITLE, WARNING } from '../../../tools/i18n/open-translation-pr.mjs'

function setup({ prExists = false, pending = false, failOn, env = {} } = {}) {
	const dir = mkdtempSync(path.join(tmpdir(), 'otp-'))
	const calls = []
	let body
	const exec = (command, args) => {
		calls.push([command, ...args])
		if (args[0] === 'pr' && args[1] !== 'view') body = readFileSync(args[args.indexOf('--body-file') + 1], 'utf8')
		if (command === 'gh' && args[1] === 'view') return { status: prExists ? 0 : 1, stdout: '', stderr: '' }
		const bad = failOn === args[0]
		return { status: bad ? 1 : 0, stdout: '', stderr: bad ? 'boom' : '' }
	}
	const logged = []
	const full = { GH_TOKEN: 'sekret', SUMMARY: '3 keys', TRANSLATION_BRANCH: 'chore/fr', GITHUB_REPOSITORY: 'o/r', RUNNER_TEMP: dir, ...env }
	return { calls, logged, body: () => body, run: () => main({ env: full, exec, log: (l) => logged.push(l), cwd: '/w', exists: () => pending }) }
}

describe('open translation pr', () => {
	it('builds the body from the summary and the reading instructions', () => {
		const body = prBody('3 keys')
		assert.ok(body.startsWith('3 keys.\n\nGenerated by `.github/workflows/i18n-translate.yml` from `locales/en-CA.json`.\n'))
		assert.ok(body.endsWith('See `.spec/decisions/ADR-0021-ci-translation-opens-a-pull-request.md`.\n'))
	})

	it('commits, force-pushes, and creates the pull request', () => {
		const t = setup()
		assert.equal(t.run(), 0)
		assert.deepEqual(t.calls.map((call) => call.slice(0, 3).join(' ')), [
			'git config user.name',
			'git config user.email',
			'git remote set-url',
			'git switch -C',
			'git add locales/fr-CA.json',
			'git commit -m',
			'git push --force',
			'gh pr view',
			'gh pr create',
		])
		assert.deepEqual(t.calls[5], ['git', 'commit', '-m', PR_TITLE, '-m', '3 keys.'])
		assert.deepEqual(t.calls[6], ['git', 'push', '--force', 'origin', 'chore/fr'])
		assert.deepEqual(t.calls[8].slice(0, 9), ['gh', 'pr', 'create', '--base', 'main', '--head', 'chore/fr', '--title', PR_TITLE])
		assert.equal(t.body(), prBody('3 keys'))
	})

	it('stages the pending sentinel when it exists', () => {
		const t = setup({ pending: true })
		t.run()
		assert.deepEqual(t.calls[5], ['git', 'add', 'locales/.fr-CA.pending'])
	})

	it('edits the open pull request instead of creating another', () => {
		const t = setup({ prExists: true })
		assert.equal(t.run(), 0)
		assert.equal(t.calls.at(-1)[2], 'edit')
		assert.equal(t.logged.at(-1), 'Updated the open translation pull request.')
	})

	it('warns about the built-in token', () => {
		const t = setup({ env: { USING_DEFAULT_TOKEN: 'true' } })
		t.run()
		assert.equal(t.logged[0], WARNING)
	})

	it('stops at a failed command without printing the token', () => {
		const t = setup({ failOn: 'push' })
		assert.equal(t.run(), 1)
		assert.deepEqual(t.logged, ['::error::git push failed: boom'])
		assert.ok(!t.calls.some((call) => call[0] === 'gh'))
	})
})
