using HpacSafety.Core.Features.QuestionBank;

namespace HpacSafety.Infrastructure.Persistence.Seeding;

/// <summary>
///     The question bank a clean database seeds — the organization's real
///     Typeform form, mapped through <c>TypeformQuestionMapper</c> against the
///     checked-in <c>form-en.json</c>/<c>form-fr.json</c> fixtures and reviewed
///     by hand the same way an Administrator reviews any import (ADR-0077,
///     ADR-0078): every French choice or question the mapper flagged as
///     defaulted to English was translated here, and privacy/system/role are
///     editorial decisions the mapper never makes.
/// </summary>
/// <remarks>
///     <para>
///         Three fields in the source form carry real branching logic
///         (<c>Where:</c> gates on <c>Country:</c>; <c>Pilot injury:</c> and
///         <c>Passenger injury:</c> gate later fields) that the importer
///         deliberately never auto-maps — Typeform's model is "jump to a
///         different field next," not "show or hide this one question," and
///         only a genuinely reducible single-parent gate is ever auto-mapped.
///         None of the three reduce that way, so every seeded question here
///         asks unconditionally; an Administrator wires the equivalent
///         "Only ask when another question is answered a certain way" setting
///         by hand once the bank is live.
///     </para>
///     <para>
///         The attachment question departs from the Typeform wording on purpose.
///         Typeform took one file and asked for the rest by email; this form takes
///         several, so it asks for photos, videos, or documents. The
///         <c>WordAttachmentQuestionForSeveralFiles</c> migration carries the same
///         correction to a database seeded with the old wording.
///     </para>
/// </remarks>
public static class QuestionBankSeed
{
	/// <summary>
	///     The instant every seeded row is stamped with. Fixed, so that applying
	///     the migration twice on two databases produces identical rows.
	/// </summary>
	public static readonly DateTimeOffset SeededAt = new(2026, 8, 22, 0, 0, 0, TimeSpan.Zero);

	/// <summary>The seeded form, in display order.</summary>
	public static IReadOnlyList<SeededQuestion> Questions { get; } =
	[
		new(
			"ae64873d_c535_4f6b_b8a3_6c50e3062f4c",
			QuestionType.Statement,
			QuestionRole.None,
			false,
			false,
			false,
			"Tell us as much as you can about the occurrence",
			"Dites-nous tout ce que vous pouvez au sujet de l'événement",
			"We will first ask you 15 short questions about the pilot, location, aircraft, injury, and damage.\nWe will then ask you to provide a detailed description of the occurrence, and the corrective actions that were taken after the occurrence (along with your recommendations).\nYou can type in your description or prepare it in advance and copy-paste it. You can leave the form and come back to it. Your answers are saved in your browser for 15 days or until you submit the form. ",
			"Nous allons en premier vous demander de répondre à 15 brèves questions au sujet du pilote, du lieu, de l'aéronef, des blessures et des dommages.\nNous allons ensuite vous inviter à donner une description détaillée de l'évènement et de décrire les actions correctives prises suite à l'évènement (ainsi que vos suggestions).\nVous pouvez remplir le signalement ou la préparer à l'avance et copier-coller le texte. Vous pouvez fermer le formulaire de signalement et y revenir plus tard. Vos réponses sont sauvegardées dans votre navigateur pendant 15 jours ou jusqu'à la soumission du formulaire.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"01hd6vk528fxpra3wcnsadr5qq",
			QuestionType.Group,
			QuestionRole.None,
			false,
			false,
			false,
			"From:",
			"Qui :",
			"Tell us who is reporting the occurrence.",
			"Dites-nous qui signale l'événement.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"da89ae06_f229_4f38_8faa_e9c5bafef2f3",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"First name",
			"Prénom",
			null,
			null,
			null,
			null,
			null,
			null,
			"01hd6vk528fxpra3wcnsadr5qq",
			false,
			[]),
		new(
			"3d662189_41cb_4430_9db8_7b2e4861df53",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"Last name",
			"Nom de famille",
			null,
			null,
			null,
			null,
			null,
			null,
			"01hd6vk528fxpra3wcnsadr5qq",
			false,
			[]),
		new(
			"65ed41c8_5fbd_4fb0_9ec3_5dabdb42d7be",
			QuestionType.Phone,
			QuestionRole.None,
			true,
			false,
			false,
			"Phone number",
			"Numéro de téléphone",
			null,
			null,
			null,
			null,
			null,
			null,
			"01hd6vk528fxpra3wcnsadr5qq",
			false,
			[]),
		new(
			"d4cded5e_1393_47e1_b703_d44e2865ccd8",
			QuestionType.Email,
			QuestionRole.None,
			true,
			false,
			false,
			"Email",
			"Courriel",
			null,
			null,
			null,
			null,
			null,
			null,
			"01hd6vk528fxpra3wcnsadr5qq",
			false,
			[]),
		new(
			"f9a22e64_b121_4dd0_b28a_6d30b9d1f7da",
			QuestionType.Group,
			QuestionRole.None,
			false,
			false,
			false,
			"Pilot:",
			"Pilote:",
			"Tell us who was the pilot in command.",
			"Dites-nous qui est le pilote aux commandes.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"52afac6c_b30c_4bd2_a052_212fa9249a45",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"First name",
			"Prénom",
			null,
			null,
			null,
			null,
			null,
			null,
			"f9a22e64_b121_4dd0_b28a_6d30b9d1f7da",
			false,
			[]),
		new(
			"41c4d104_82c5_4f31_9d86_cb95e35622e4",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"Last name",
			"Nom de famille",
			null,
			null,
			null,
			null,
			null,
			null,
			"f9a22e64_b121_4dd0_b28a_6d30b9d1f7da",
			false,
			[]),
		new(
			"db18ab92_b23d_4d21_af63_310f24e1a0bb",
			QuestionType.MultiSelect,
			QuestionRole.None,
			false,
			false,
			false,
			"Pilot's ratings:",
			"Qualifications du pilote:",
			"What are the pilot's most advanced HPAC ratings?",
			"Quelles sont les qualifications ACVL les plus avancées du pilote?",
			null,
			null,
			null,
			null,
			null,
			true,
			[
				new("7f59339d-ef72-4c5c-b638-c951ef3e7b03", "Student", "Élève"),
				new("130b26cb-234c-4c2b-ab5c-508f4a423a72", "P1", "P1"),
				new("60919e51-e13d-4557-a34a-e1515341cfa1", "P2", "P2"),
				new("686678eb-5ae5-41e2-a12b-5586b096e3d4", "P3", "P3"),
				new("ddc351e6-6930-40c7-88ce-56e55312d548", "P4", "P4"),
				new("f797fa85-8fac-4bc2-87df-1bbef00233b1", "H1", "H1"),
				new("ddb04b17-2ea6-4989-8275-d98d2345f7d4", "H2", "H2"),
				new("9ed31e44-047b-425e-8749-18e4a41991e9", "H3", "H3"),
				new("b04a07c3-78d9-4cec-b55f-a023ef44f2c8", "H4", "H4"),
				new("45849d8b-7035-43c6-99fd-c87ca2a3f3f3", "Paragliding Instructor", "Instructeur parapente"),
				new("04b0718a-9018-4915-aed1-4390597108dc", "Paragliding Tandem", "Biplace parapente"),
				new("6f9c2f55-a0df-4afa-9744-9681b60933dd", "Hang Gliding Instructor", "Instructeur deltaplane"),
				new("a0df6911-7b44-4483-bd90-288eb15ac2bd", "Hang Gliding Tandem", "Biplace deltaplane"),
			]),
		new(
			"c923604b_0aab_4223_92bb_795d77535f57",
			QuestionType.Date,
			QuestionRole.None,
			false,
			false,
			false,
			"Date:",
			"Date:",
			"Tell us the date of the occurrence.",
			"À quelle date l'évènement a-t-il eu lieu?",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"5d0277fa_67fd_464e_9aef_f419deef7500",
			QuestionType.SingleSelect,
			QuestionRole.None,
			false,
			false,
			false,
			"Time of day:",
			"Moment de la journée:",
			"Tell us the time of the occurrence.",
			"À quel moment de la journée l'évènement a-t-il eu lieu?",
			null,
			null,
			null,
			null,
			null,
			false,
			[
				new("d438fd30-426d-4f2f-9ae6-0f9e0b0fa2bc", "Morning", "Matin"),
				new("7b802157-7c6a-41da-a73c-a98c72eeefdd", "Mid-day", "Midi"),
				new("d61d3da3-63b1-4847-8674-29304fb234f2", "Afternoon", "Après-midi"),
				new("2abeacb3-c245-4a62-8ec9-f73d928aa15c", "Evening", "Soir"),
				new("682ce5a1-fc01-459f-bfb3-c75402160098", "Do not know", "Je ne sais pas"),
			]),
		new(
			"2a401575_8cf4_4c87_b8df_95798d07a772",
			QuestionType.YesNo,
			QuestionRole.None,
			false,
			false,
			false,
			"Country:",
			"Pays:",
			"Did the occurrence happen in Canada?",
			"L'évènement a-t-il eu lieu au Canada?",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"56bd800a_2af4_45fd_b4b9_16cbf250bc56",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"Where:",
			"Où:",
			"Tell us the location of the occurrence.",
			"Indiquez le lieu de l'événement.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"849ea0c4_b36e_44a7_936e_e578967907a3",
			QuestionType.SingleSelect,
			QuestionRole.None,
			false,
			false,
			false,
			"Province:",
			"Province:",
			"Tell us the province of the occurrence.",
			"Dans quelle province a eu lieu l'évènement?",
			null,
			null,
			null,
			null,
			null,
			false,
			[
				new("10fa880e-cbbc-4e1f-821b-d411a0a94cab", "Newfoundland and Labrador", "Terre-Neuve-et-Labrador"),
				new("afa686b7-5080-4f4b-a490-44348e80f443", "Prince Edward Island", "Île-du-Prince-Édouard"),
				new("e88fda61-bd11-477e-816a-53a120cc7c44", "Nova Scotia", "Nouvelle-Écosse"),
				new("2d823eb9-cd71-453a-a3ec-85ca6742f969", "New Brunswick", "Nouveau-Brunswick"),
				new("c6064aa5-d65b-4af9-b86a-6ed5bf0648cc", "Quebec", "Québec"),
				new("5c686994-87f6-472e-b9f4-227408e58ea8", "Ontario", "Ontario"),
				new("e5cb6f21-7cd1-4318-bc75-80d16ce84da0", "Manitoba", "Manitoba"),
				new("1ea238c3-514e-4750-8da3-bc041dccdc0e", "Saskatchewan", "Saskatchewan"),
				new("eb5e663a-88e4-4dee-b605-2fcd2172df40", "Alberta", "Alberta"),
				new("f22600ad-796e-444b-bd42-915839f74f9a", "British Columbia", "Colombie-Britannique"),
				new("3e5d0f04-9bd8-482c-b16f-678ac519c742", "Yukon", "Yukon"),
				new("84a5d475-c571-4462-9063-47967a0e5b69", "Northwest Territories", "Territoires du Nord-Ouest"),
				new("db9ea823-8e51-473f-ac07-7aca41de9a8e", "Nunavut", "Nunavut"),
			]),
		new(
			"b86820e5_114e_4266_b971_03b959e74167",
			QuestionType.Group,
			QuestionRole.None,
			false,
			false,
			false,
			"Aircraft:",
			"Aéronef:",
			"Tell us more about the aircraft(s) involved in the occurrence.",
			"Dites-nous en plus au sujet de ou des aéronefs impliqués dans l'évènement.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"7590a371_c9cd_4e19_9954_be5137a669d2",
			QuestionType.MultiSelect,
			QuestionRole.None,
			false,
			false,
			false,
			"Type of aircraft:",
			"Type d'aéronef:",
			"Tell us the type of aircraft(s) involved in the occurrence.",
			"Listez le(s) type(s) d'aéronef(s) impliqué(s) dans l'évènement.",
			null,
			null,
			null,
			null,
			"b86820e5_114e_4266_b971_03b959e74167",
			true,
			[
				new("83f0a905-e85d-40a8-a195-2398d5c8575d", "Paraglider", "Parapente"),
				new("e5d64953-6c18-4014-a986-3c421f4c39ad", "Hang Glider", "Deltaplane"),
				new("2b331328-3c61-4bfa-b463-1c1e45ed5e69", "Mini Wing", "Aile mini"),
				new("a32a95eb-d84c-4787-97ae-8add7cca1a9a", "Speedflyer", "Speedflyer"),
				new("c4d2f82c-783b-471b-b67d-f4e4c67eda45", "Paraglider Tandem", "Tandem Parapente"),
				new("7cce136a-27ed-4f05-9c5d-7a2941d4dc77", "Hang Glider Tandem", "Tandem Deltaplane"),
			]),
		new(
			"7018ad9b_bc9c_4f06_9a36_5fb3eed0368c",
			QuestionType.ShortText,
			QuestionRole.None,
			false,
			false,
			false,
			"Manufacturer:",
			"Manufacturier:",
			"Tell us the manufacturer of the pilot's aircraft.",
			"Indiquez le manufacturier de l'aéronef du pilote.",
			null,
			null,
			null,
			null,
			"b86820e5_114e_4266_b971_03b959e74167",
			false,
			[]),
		new(
			"762e8ce8_ccd3_4d1f_be09_68eb33136aa5",
			QuestionType.ShortText,
			QuestionRole.None,
			false,
			false,
			false,
			"Model:",
			"Modèle:",
			"Tell us about the model of the pilot's aircraft.",
			"Indiquez le modèle de l'aéronef du pilote.",
			null,
			null,
			null,
			null,
			"b86820e5_114e_4266_b971_03b959e74167",
			false,
			[]),
		new(
			"6879f513_fe00_4bdc_acda_138947650b3c",
			QuestionType.ShortText,
			QuestionRole.None,
			false,
			false,
			false,
			"Certification:",
			"Homologation:",
			"Tell us about the certification of the pilot's aircraft.",
			"Quelle est l'homologation de l'aéronef du pilote.",
			null,
			null,
			null,
			null,
			"b86820e5_114e_4266_b971_03b959e74167",
			false,
			[]),
		new(
			"a07c69aa_8602_484a_97b0_df4bf6c703c2",
			QuestionType.SingleSelect,
			QuestionRole.None,
			true,
			false,
			false,
			"Pilot injury:",
			"Blessure (pilote):",
			"If any, tell us the type of injury to the pilot.",
			"S'il y a lieu, indiquez le type de blessure de la ou du pilote.",
			null,
			null,
			null,
			null,
			null,
			false,
			[
				new("d42b69e9-93ec-4e34-93e9-9489c50984e9", "No injury", "Pas de blessure"),
				new("a3c9207c-19f7-4b47-9f14-6e4c216c1045", "Minor injury (no medical aid or on-site aid only)", "Blessure légère (aucun soin ou secours sur site uniquement)"),
				new("1a9e28c4-d273-495d-8ba0-717978bb090d", "Serious injury (secondary medical aid)", "Blessure grave (aide médicale secondaire)"),
				new("8cab0098-f2ae-41ee-8c20-74c080165bba", "Fatality", "Décès"),
				new("4016f30b-2b58-4a11-a268-b9c8da7669bf", "Do not know", "Ne sait pas"),
			]),
		new(
			"1e24c3db_5bde_464c_af83_e528126050c5",
			QuestionType.SingleSelect,
			QuestionRole.None,
			true,
			false,
			false,
			"Passenger injury:",
			"Blessure (passagère, passager):",
			"If any, tell us the type of injury to the passenger.",
			"S'il y a lieu, indiquez le type de blessure de la passagère ou du passager.",
			null,
			null,
			null,
			null,
			null,
			false,
			[
				new("00bccdf4-0e96-4d78-a19b-d77c1ba95532", "No injury", "Pas de blessure"),
				new("121e466d-32aa-42c2-85eb-4ef419e7752c", "Minor injury (no medical aid or on-site aid only)", "Blessure légère (aucun soin ou secours sur site uniquement)"),
				new("69a9e30c-77f0-4404-85b6-e57231630fb2", "Serious injury (secondary medical aid)", "Blessure grave (aide médicale secondaire)"),
				new("bfb55a56-d8c8-4f17-9053-7a56472f2528", "Fatality", "Décès"),
				new("72b46fe4-4b42-47bf-b197-fc679e1477d9", "Do not know", "Ne sait pas"),
			]),
		new(
			"d47bfadd_1ea1_40c6_bbdc_9b6084ee941f",
			QuestionType.ShortText,
			QuestionRole.None,
			true,
			false,
			false,
			"Injury description:",
			"Description de la blessure:",
			"If any, describe the injury.",
			"S'il y a lieu, décrivez la blessure.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"f3051ab2_4225_407a_9ba4_073146bd3fdb",
			QuestionType.ShortText,
			QuestionRole.None,
			false,
			false,
			false,
			"Damage:",
			"Dommages:",
			"If any, describe the damage to the aircraft, environment, or property.",
			"S'il y a lieu, décrivez les dommages à l'aéronef, à l'environnement ou à la propriété.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"2a27ebe1_5b93_465f_bf67_e3248429d6f8",
			QuestionType.LongText,
			QuestionRole.None,
			false,
			false,
			false,
			"Description:",
			"Description:",
			"Give a precise description of the occurrence. What happened to the aircraft, what did you see, hear, or do? Include your *role* in the occurrence. Think *preflight*, *weather*, *distractions*, *emotions*. Include your thoughts about the *causes* for the incident or accident.",
			"Faites une description détaillée de l'événement. Qu'est-il arrivé à l'aéronef, qu'avez-vous vu, entendu, ou fait? Précisez votre *rôle* dans l'événement. Pensez à la *prévol*, à la *météo*, aux *distractions*, aux *émotions*. Ajoutez vos réflexions quant aux causes de l'incident ou de l'accident.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"d1ba440d_a08a_4398_9481_7b3a36e337f7",
			QuestionType.LongText,
			QuestionRole.None,
			false,
			false,
			false,
			"Action and prevention:",
			"Action et prévention:",
			"Tell us what actions were taken after the occurrence. Include your thoughts for prevention.",
			"Indiquez les actions prises suite à l'événement. Ajoutez vos réflexions au sujet de la prévention.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"418e72ec_1edc_4e0d_9429_af65ca564ab1",
			QuestionType.FileUpload,
			QuestionRole.None,
			true,
			false,
			false,
			"Photos or videos:",
			"Photos ou vidéos:",
			"Upload photos, videos, or documents of the occurrence, if you have any.",
			"Téléversez des photos, vidéos ou documents de l'événement, si vous en avez.",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
		new(
			"08f3eedb_e682_431d_be9b_2d83765bf022",
			QuestionType.YesNo,
			QuestionRole.ConsentPublish,
			true,
			true,
			true,
			"Publication consent",
			"Autorisation de publication",
			"Occurrence reports help our entire community. Do you agree for HPAC to publish a de-identified (no name, location, and other identifiable factors) version of your report on its website?",
			"Les signalements d'événements aident toute notre communauté. Acceptez-vous que l'ACVL publie sur son site Web une version dépersonnalisée (sans nom, lieu ni autre facteur identifiable) de votre signalement?",
			null,
			null,
			null,
			null,
			null,
			false,
			[]),
	];
}
