import type { Locale } from "./locales"

export type Catalogue = Record<string, string>

function flatten(value: unknown, prefix = ""): Catalogue {
	const result: Catalogue = {}
	for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
		const path = prefix ? `${prefix}.${key}` : key
		if (typeof entry === "string") {
			result[path] = entry
		} else if (entry !== null && typeof entry === "object") {
			Object.assign(result, flatten(entry, path))
		}
	}
	return result
}

// locales/*.json live at the repository root (../../../../ from here — see
// vite.config.ts). Both catalogues are built into the page's own bundle
// (eager), never fetched as a chunk afterwards: a deploy deletes the previous
// build's hashed chunks, so a tab left open across one would fail to fetch a
// lazy catalogue and show raw keys until reloaded (REQ-WLD-049, #805).
//
// The glob names en-CA and fr-CA only, so the other files in locales/
// (fr-CA.meta.json, glossary.json, terms.json) never reach the browser.
// fr-CA.json is generated by .github/workflows/i18n-translate.yml (ADR-0021)
// and may not exist locally yet; a glob that matches no file builds anyway,
// and every locale is merged over English, so a key missing from a locale —
// or a locale with no file at all — falls back to its English text.
const modules: Partial<Record<string, unknown>> = import.meta.glob("../../../../locales/{en-CA,fr-CA}.json", {
	eager: true,
	import: "default",
})

function raw(locale: Locale): Catalogue {
	const module = modules[`../../../../locales/${locale}.json`]
	return module ? flatten(module) : {}
}

const english = raw("en-CA")
const catalogues = new Map<Locale, Catalogue>([["en-CA", english]])

/** English-backed catalogue for `locale`: every key falls back to English when absent. */
export function catalogueFor(locale: Locale): Catalogue {
	let catalogue = catalogues.get(locale)
	if (!catalogue) {
		catalogue = { ...english, ...raw(locale) }
		catalogues.set(locale, catalogue)
	}
	return catalogue
}
