import type { Locale } from "./locales"

export type Catalogue = Record<string, string>

function flatten(value: unknown, prefix = ""): Catalogue {
	const result: Catalogue = {}
	for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
		const path = prefix ? `${prefix}.${key}` : key
		if (typeof entry === "string") {
			result[path] = entry
		} else if (entry !== null && typeof entry === "object") {
			Object.assign(result, flatten(entry, path))
		}
	}
	return result
}

// locales/*.json live at the repository root (../../../../ from here — see
// vite.config.ts). fr-CA.json is generated by
// .github/workflows/i18n-translate.yml after the first en-CA merge to main
// (ADR-0021) and is never hand-authored, so it may not exist locally or in
// CI yet. Importing it eagerly here would break the build the moment it is
// absent, so every catalogue is loaded lazily and merged over English —
// any key missing from a locale, including a locale with no file at all,
// falls back to its English text rather than a raw key or a crash.
const modules = import.meta.glob<{ default: unknown }>("../../../../locales/*.json")

async function loadRaw(locale: Locale): Promise<Catalogue | null> {
	const path = `../../../../locales/${locale}.json`
	const importer = modules[path]
	if (!importer) return null
	try {
		const module = await importer()
		return flatten(module.default)
	} catch {
		return null
	}
}

let englishCache: Promise<Catalogue> | null = null

function loadEnglish(): Promise<Catalogue> {
	englishCache ??= loadRaw("en-CA").then((catalogue) => catalogue ?? {})
	return englishCache
}

/** English-backed catalogue for `locale`: every key falls back to English when absent. */
export async function loadCatalogue(locale: Locale): Promise<Catalogue> {
	const english = await loadEnglish()
	if (locale === "en-CA") return english

	const translated = await loadRaw(locale)
	return { ...english, ...translated }
}
