// <auto-generated />
using System;
using HpacSafety.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HpacSafety.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HpacSafetyDbContext))]
    [Migration("20260925235946_ReviewTypeAheadValues")]
    partial class ReviewTypeAheadValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HpacSafety.Core.Features.Comments.ReportComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AuthorSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("author_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<string>("HiddenBySubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hidden_by_subject");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_report_comments");

                    b.HasIndex("ReportId", "CreatedAt")
                        .HasDatabaseName("ix_report_comments_report_id_created_at");

                    b.ToTable("report_comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_comments_hidden_coherence", "(hidden_at IS NULL) = (hidden_by_subject IS NULL)");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Comments.ReportCommentRevision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("comment_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("text");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.Property<string>("TranslationSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("translation_source");

                    b.HasKey("Id")
                        .HasName("pk_report_comment_revisions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_report_comment_revisions_created_at")
                        .HasFilter("translated_text IS NULL AND deleted IS NULL");

                    b.HasIndex("CommentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_report_comment_revisions_comment_id_number");

                    b.ToTable("report_comment_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_comment_revisions_locale", "locale IN ('en-CA', 'fr-CA')");

                            t.HasCheckConstraint("ck_report_comment_revisions_translation_coherence", "(translated_text IS NULL) = (translation_source IS NULL)");

                            t.HasCheckConstraint("ck_report_comment_revisions_translation_source", "translation_source IS NULL OR translation_source = 'auto'");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AuditLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorSubject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("actor_subject");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("target_id")
                        .IsFixedLength();

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("ActorSubject")
                        .HasDatabaseName("ix_audit_log_actor_subject");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_log_target_type_target_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("aggregate_id")
                        .IsFixedLength();

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PoisonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("poisoned_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_outbox_messages_aggregate_id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_claimable")
                        .HasFilter("processed_at IS NULL AND poisoned_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_type", "type IN ('summarize_report', 'process_attachment', 'translate_answers', 'translate_comment', 'translate_choice')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_key")
                        .HasFilter("deleted IS NULL");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_questions_role", "role IN ('none', 'consent_publish', 'consent_media')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionChoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<bool>("AddedByReporter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("added_by_reporter");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("LabelEn")
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelEnSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("label_en_source");

                    b.Property<string>("LabelFr")
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<string>("LabelFrSource")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("label_fr_source");

                    b.Property<bool>("NeedsReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("needs_review");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<string>("ReporterLocale")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("reporter_locale");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("pk_question_choices");

                    b.HasIndex("QuestionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_question_choices_question_id_code");

                    b.ToTable("question_choices", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_choices_label", "label_en IS NOT NULL AND label_fr IS NOT NULL OR (added_by_reporter OR deleted IS NOT NULL) AND (label_en IS NOT NULL OR label_fr IS NOT NULL)");

                            t.HasCheckConstraint("ck_question_choices_label_source", "(label_en_source IS NULL OR label_en_source IN ('human', 'auto')) AND (label_fr_source IS NULL OR label_fr_source IN ('human', 'auto')) AND (label_en IS NULL) = (label_en_source IS NULL) AND (label_fr IS NULL) = (label_fr_source IS NULL)");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("DependsOnOptionCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("depends_on_option_code");

                    b.Property<string>("DependsOnQuestionId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("depends_on_question_id")
                        .IsFixedLength();

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("GroupedUnderQuestionId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("grouped_under_question_id")
                        .IsFixedLength();

                    b.Property<string>("HelpTextEn")
                        .HasColumnType("text")
                        .HasColumnName("help_text_en");

                    b.Property<string>("HelpTextFr")
                        .HasColumnType("text")
                        .HasColumnName("help_text_fr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<bool>("IsTranslatable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_translatable");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<string>("PlaceholderEn")
                        .HasColumnType("text")
                        .HasColumnName("placeholder_en");

                    b.Property<string>("PlaceholderFr")
                        .HasColumnType("text")
                        .HasColumnName("placeholder_fr");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_question_revisions");

                    b.HasIndex("DependsOnQuestionId")
                        .HasDatabaseName("ix_question_revisions_depends_on_question_id");

                    b.HasIndex("GroupedUnderQuestionId")
                        .HasDatabaseName("ix_question_revisions_grouped_under_question_id");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_question_revisions_is_active_display_order");

                    b.HasIndex("QuestionId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_question_revisions_question_id_revision_number");

                    b.ToTable("question_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_revisions_translatable_text", "NOT is_translatable OR type IN ('short_text', 'long_text')");

                            t.HasCheckConstraint("ck_question_revisions_type", "type IN ('short_text', 'long_text', 'email', 'phone', 'date', 'number', 'single_select', 'multi_select', 'yes_no', 'checkbox', 'file_upload', 'statement', 'group', 'time', 'autocomplete')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Typeform.PendingImportLogic", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FieldRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("field_ref");

                    b.Property<string>("FieldTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_title");

                    b.Property<string>("ImportBatchId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("import_batch_id")
                        .IsFixedLength();

                    b.Property<string>("RawLogicJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_logic_json");

                    b.HasKey("Id")
                        .HasName("pk_pending_import_logic");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_pending_import_logic_import_batch_id");

                    b.ToTable("pending_import_logic", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<bool?>("ConsentDocuments")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_documents");

                    b.Property<bool?>("ConsentMedia")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_media");

                    b.Property<bool?>("ConsentPublish")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_publish");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SummaryError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary_error");

                    b.Property<string>("UnpublishNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("unpublish_note");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_reports_status_submitted_at");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_language", "language IN ('en-CA', 'fr-CA')");

                            t.HasCheckConstraint("ck_reports_status", "status IN ('submitted', 'summarizing', 'summary_failed', 'pending', 'published', 'unpublished')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean")
                        .HasColumnName("value_boolean");

                    b.Property<string>("ChoiceId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("choice_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("question_key");

                    b.Property<string>("QuestionRevisionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_revision_id")
                        .IsFixedLength();

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("TranslatedValue")
                        .HasColumnType("text")
                        .HasColumnName("translated_value");

                    b.Property<string>("TranslationMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("translation_mode");

                    b.Property<string>("TranslationSource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("translation_source");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_report_answers");

                    b.HasAlternateKey("ReportId", "Id")
                        .HasName("ak_report_answers_report_id_id");

                    b.HasIndex("AnsweredAt")
                        .HasDatabaseName("ix_report_answers_answered_at")
                        .HasFilter("value IS NOT NULL AND translated_value IS NULL AND translation_mode = 'machine' AND choice_id IS NULL");

                    b.HasIndex("ChoiceId")
                        .HasDatabaseName("ix_report_answers_choice_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_report_answers_question_id");

                    b.HasIndex("QuestionRevisionId")
                        .HasDatabaseName("ix_report_answers_question_revision_id");

                    b.HasIndex("ReportId", "QuestionId")
                        .HasDatabaseName("ix_report_answers_report_id_question_id");

                    b.ToTable("report_answers", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_answers_boolean_has_no_words", "value_boolean IS NULL OR (translated_value IS NULL AND translation_source IS NULL AND translation_mode = 'none')");

                            t.HasCheckConstraint("ck_report_answers_text_or_boolean", "value IS NULL OR value_boolean IS NULL");

                            t.HasCheckConstraint("ck_report_answers_translation_mode", "translation_mode IN ('none', 'choice', 'machine')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("ExifStrippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exif_stripped_at");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<string>("HiddenBySubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("hidden_by_subject");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ProcessingErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("processing_error_code");

                    b.Property<string>("ReportAnswerId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_answer_id")
                        .IsFixedLength();

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("StrippedBlobKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stripped_blob_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.HasKey("Id")
                        .HasName("pk_report_files");

                    b.HasIndex("ExifStrippedAt")
                        .HasDatabaseName("ix_report_files_exif_stripped_at")
                        .HasFilter("exif_stripped_at IS NULL");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_files_report_id");

                    b.HasIndex("ReportId", "ReportAnswerId")
                        .HasDatabaseName("ix_report_files_report_id_report_answer_id");

                    b.ToTable("report_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_files_exif_stripped_coherence", "(exif_stripped_at IS NULL) = (stripped_blob_key IS NULL)");

                            t.HasCheckConstraint("ck_report_files_hidden_coherence", "(hidden_at IS NULL) = (hidden_by_subject IS NULL)");

                            t.HasCheckConstraint("ck_report_files_kind", "kind IN ('image', 'video', 'document')");

                            t.HasCheckConstraint("ck_report_files_validated_document", "validated_at IS NULL OR kind = 'document'");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AiSummaryEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_en");

                    b.Property<string>("AiSummaryFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_fr");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBySubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("approved_by_subject");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("SourceEn")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_en");

                    b.Property<string>("SourceFr")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_fr");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_summaries");

                    b.HasIndex("ReportId")
                        .IsUnique()
                        .HasDatabaseName("ix_summaries_report_id");

                    b.ToTable("summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_summaries_approval_coherence", "(approved_by_subject IS NULL) = (approved_at IS NULL)");

                            t.HasCheckConstraint("ck_summaries_source_en", "source_en IN ('generated', 'human', 'machine')");

                            t.HasCheckConstraint("ck_summaries_source_fr", "source_fr IN ('generated', 'human', 'machine')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.AdminPendingCounts", b =>
                {
                    b.Property<int>("AnswersAwaitingTranslation")
                        .HasColumnType("integer")
                        .HasColumnName("answers_awaiting_translation");

                    b.Property<int>("ReportsNeedingAction")
                        .HasColumnType("integer")
                        .HasColumnName("reports_needing_action");

                    b.Property<int>("TypeAheadValuesAwaitingReview")
                        .HasColumnType("integer")
                        .HasColumnName("type_ahead_values_awaiting_review");

                    b.ToTable((string)null);

                    b.ToView("admin_pending_counts", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.AdminReportQueueItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<bool?>("ConsentPublish")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_publish");

                    b.Property<bool>("IsStuck")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stuck");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<bool>("NeedsAction")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_action");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_admin_report_queue");

                    b.ToTable((string)null);

                    b.ToView("admin_report_queue", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.AnswerAwaitingTranslation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_answers_awaiting_translation");

                    b.ToTable((string)null);

                    b.ToView("answers_awaiting_translation", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.PublicReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AiSummaryEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_en");

                    b.Property<string>("AiSummaryFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_fr");

                    b.Property<int>("CommentCount")
                        .HasColumnType("integer")
                        .HasColumnName("comment_count");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_public_reports");

                    b.ToTable((string)null);

                    b.ToView("public_reports", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.PublicReportComment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AuthorSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_subject");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Edited")
                        .HasColumnType("boolean")
                        .HasColumnName("edited");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("locale");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_public_report_comments");

                    b.ToTable((string)null);

                    b.ToView("public_report_comments", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Infrastructure.Persistence.Views.PublicReportMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("DocumentBlobKey")
                        .HasColumnType("text")
                        .HasColumnName("document_blob_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("StrippedBlobKey")
                        .HasColumnType("text")
                        .HasColumnName("stripped_blob_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_public_report_media");

                    b.ToTable((string)null);

                    b.ToView("public_report_media", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Comments.ReportComment", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_comments_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Comments.ReportCommentRevision", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Comments.ReportComment", null)
                        .WithMany("Revisions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_comment_revisions_report_comments_comment_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionChoice", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany("AllChoices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_choices_questions_question_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevision", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany()
                        .HasForeignKey("DependsOnQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_question_revisions_questions_depends_on_question_id");

                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany()
                        .HasForeignKey("GroupedUnderQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_question_revisions_questions_grouped_under_question_id");

                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany("Revisions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_revisions_questions_question_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.QuestionChoice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_report_answers_question_choices_choice_id");

                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_questions_question_id");

                    b.HasOne("HpacSafety.Core.Features.QuestionBank.QuestionRevision", null)
                        .WithMany()
                        .HasForeignKey("QuestionRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_question_revisions_question_revision_id");

                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Answers")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_reports_report_id");

                    b.Navigation("Choice");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Files")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_files_reports_report_id");

                    b.HasOne("HpacSafety.Core.Features.Reporting.ReportAnswer", null)
                        .WithMany()
                        .HasForeignKey("ReportId", "ReportAnswerId")
                        .HasPrincipalKey("ReportId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_report_files_report_answers_report_id_report_answer_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithOne("Summary")
                        .HasForeignKey("HpacSafety.Core.Features.Reporting.Summary", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Comments.ReportComment", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Navigation("AllChoices");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Files");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
