// <auto-generated />
using System;
using HpacSafety.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HpacSafety.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HpacSafetyDbContext))]
    [Migration("20260823043129_AddReportFilesAndPerLocaleSummaries")]
    partial class AddReportFilesAndPerLocaleSummaries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_subject");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AuditLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("admin_user_id")
                        .IsFixedLength();

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("target_id")
                        .IsFixedLength();

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_audit_log_admin_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_log_target_type_target_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("aggregate_id")
                        .IsFixedLength();

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PoisonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("poisoned_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_outbox_messages_aggregate_id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_claimable")
                        .HasFilter("processed_at IS NULL AND poisoned_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HelpEn")
                        .HasColumnType("text")
                        .HasColumnName("help_en");

                    b.Property<string>("HelpFr")
                        .HasColumnType("text")
                        .HasColumnName("help_fr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("section_key");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("SupersedesQuestionId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("supersedes_question_id")
                        .IsFixedLength();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("SupersedesQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_supersedes_question_id");

                    b.HasIndex("Key", "Revision")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_key_revision");

                    b.HasIndex("Key", "IsActive", "Revision")
                        .HasDatabaseName("ix_questions_key_is_active_revision");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionOption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_question_options_question_id_code");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<bool?>("ConsentPublish")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_publish");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SummaryError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary_error");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_reports_status_submitted_at");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("question_key");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.PrimitiveCollection<string[]>("SelectedOptionCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("selected_option_codes");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_report_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_report_answers_question_id");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_answers_report_id");

                    b.ToTable("report_answers", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("ExifStrippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exif_stripped_at");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("StrippedBlobKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stripped_blob_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_report_files");

                    b.HasIndex("ExifStrippedAt")
                        .HasDatabaseName("ix_report_files_exif_stripped_at")
                        .HasFilter("exif_stripped_at IS NULL");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_files_report_id");

                    b.ToTable("report_files", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("approved_by")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_summaries");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_summaries_approved_by");

                    b.HasIndex("ReportId", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ix_summaries_report_id_language");

                    b.ToTable("summaries", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AuditLogEntry", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Moderation.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_admin_users_admin_user_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithOne()
                        .HasForeignKey("HpacSafety.Core.Features.QuestionBank.Question", "SupersedesQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_questions_questions_supersedes_question_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionOption", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_questions_question_id");

                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Answers")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Files")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_files_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Moderation.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_summaries_admin_users_approved_by");

                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Summaries")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Files");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
