// <auto-generated />
using System;
using HpacSafety.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HpacSafety.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HpacSafetyDbContext))]
    [Migration("20260827013637_MigrateCanonicalDomainAndPersistence")]
    partial class MigrateCanonicalDomainAndPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AdminUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MemberIdentifier")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("member_identifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("MemberIdentifier")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_member_identifier")
                        .HasFilter("deleted IS NULL");

                    b.ToTable("admin_users", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_users_role", "role IN ('safety_officer', 'administrator')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AuditLogEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("AdminUserId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("admin_user_id")
                        .IsFixedLength();

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("target_id")
                        .IsFixedLength();

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_audit_log_admin_user_id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_log_occurred_at");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_log_target_type_target_id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Outbox.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("aggregate_id")
                        .IsFixedLength();

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PoisonedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("poisoned_at");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("AggregateId")
                        .HasDatabaseName("ix_outbox_messages_aggregate_id");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_outbox_messages_claimable")
                        .HasFilter("processed_at IS NULL AND poisoned_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_type", "type IN ('summarize_report')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_key");

                    b.ToTable("questions", null, t =>
                        {
                            t.HasCheckConstraint("ck_questions_role", "role IN ('none', 'consent_publish')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevision", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("HelpTextEn")
                        .HasColumnType("text")
                        .HasColumnName("help_text_en");

                    b.Property<string>("HelpTextFr")
                        .HasColumnType("text")
                        .HasColumnName("help_text_fr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<string>("PlaceholderEn")
                        .HasColumnType("text")
                        .HasColumnName("placeholder_en");

                    b.Property<string>("PlaceholderFr")
                        .HasColumnType("text")
                        .HasColumnName("placeholder_fr");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("SectionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("section_key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_question_revisions");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_question_revisions_is_active_display_order");

                    b.HasIndex("QuestionId", "RevisionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_question_revisions_question_id_revision_number");

                    b.ToTable("question_revisions", null, t =>
                        {
                            t.HasCheckConstraint("ck_question_revisions_type", "type IN ('short_text', 'long_text', 'email', 'phone', 'date', 'number', 'single_select', 'multi_select', 'yes_no', 'checkbox', 'file_upload', 'statement', 'group')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevisionOption", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_en");

                    b.Property<string>("LabelFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label_fr");

                    b.Property<string>("QuestionRevisionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_revision_id")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_question_revision_options");

                    b.HasIndex("QuestionRevisionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_question_revision_options_question_revision_id_code");

                    b.ToTable("question_revision_options", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<bool?>("ConsentPublish")
                        .HasColumnType("boolean")
                        .HasColumnName("consent_publish");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SummaryError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary_error");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("Status", "SubmittedAt")
                        .HasDatabaseName("ix_reports_status_submitted_at");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_language", "language IN ('en-CA', 'fr-CA')");

                            t.HasCheckConstraint("ck_reports_status", "status IN ('submitted', 'summarizing', 'pending_review', 'summary_failed', 'approved', 'rejected', 'published')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_id")
                        .IsFixedLength();

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("question_key");

                    b.Property<string>("QuestionRevisionId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("question_revision_id")
                        .IsFixedLength();

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.PrimitiveCollection<string[]>("SelectedOptionCodes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("selected_option_codes");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_report_answers");

                    b.HasAlternateKey("ReportId", "Id")
                        .HasName("ak_report_answers_report_id_id");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_report_answers_question_id");

                    b.HasIndex("QuestionRevisionId")
                        .HasDatabaseName("ix_report_answers_question_revision_id");

                    b.HasIndex("ReportId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_report_answers_report_id_question_id");

                    b.ToTable("report_answers", (string)null);
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("blob_key");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset?>("ExifStrippedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exif_stripped_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("ProcessingErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("processing_error_code");

                    b.Property<string>("ReportAnswerId")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_answer_id")
                        .IsFixedLength();

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<string>("StrippedBlobKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("stripped_blob_key");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_report_files");

                    b.HasIndex("ExifStrippedAt")
                        .HasDatabaseName("ix_report_files_exif_stripped_at")
                        .HasFilter("exif_stripped_at IS NULL");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_files_report_id");

                    b.HasIndex("ReportId", "ReportAnswerId")
                        .HasDatabaseName("ix_report_files_report_id_report_answer_id");

                    b.ToTable("report_files", null, t =>
                        {
                            t.HasCheckConstraint("ck_report_files_exif_stripped_coherence", "(exif_stripped_at IS NULL) = (stripped_blob_key IS NULL)");

                            t.HasCheckConstraint("ck_report_files_kind", "kind IN ('image', 'video', 'document')");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("id")
                        .IsFixedLength();

                    b.Property<string>("AiSummaryEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_en");

                    b.Property<string>("AiSummaryFr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_summary_fr");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("approved_by")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("char(11)")
                        .HasColumnName("report_id")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_summaries");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_summaries_approved_by");

                    b.HasIndex("ReportId")
                        .IsUnique()
                        .HasDatabaseName("ix_summaries_report_id");

                    b.ToTable("summaries", null, t =>
                        {
                            t.HasCheckConstraint("ck_summaries_approval_coherence", "(approved_by IS NULL) = (approved_at IS NULL)");
                        });
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Moderation.AuditLogEntry", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Moderation.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_log_admin_users_admin_user_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevision", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany("Revisions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_revisions_questions_question_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevisionOption", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.QuestionRevision", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_revision_options_question_revisions_question_revis~");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportAnswer", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.QuestionBank.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_questions_question_id");

                    b.HasOne("HpacSafety.Core.Features.QuestionBank.QuestionRevision", null)
                        .WithMany()
                        .HasForeignKey("QuestionRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_question_revisions_question_revision_id");

                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Answers")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_answers_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.ReportFile", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithMany("Files")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_report_files_reports_report_id");

                    b.HasOne("HpacSafety.Core.Features.Reporting.ReportAnswer", null)
                        .WithMany()
                        .HasForeignKey("ReportId", "ReportAnswerId")
                        .HasPrincipalKey("ReportId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_report_files_report_answers_report_id_report_answer_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Summary", b =>
                {
                    b.HasOne("HpacSafety.Core.Features.Moderation.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_summaries_admin_users_approved_by");

                    b.HasOne("HpacSafety.Core.Features.Reporting.Report", null)
                        .WithOne("Summary")
                        .HasForeignKey("HpacSafety.Core.Features.Reporting.Summary", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_summaries_reports_report_id");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.Question", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.QuestionBank.QuestionRevision", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("HpacSafety.Core.Features.Reporting.Report", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Files");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
