#!/usr/bin/env node
// Opens (or updates) the provider-relock pull request (terraform-relock.yml).
//
// Reuses the same fine-grained repository PAT i18n-translate.yml uses to open
// its pull request — the built-in GITHUB_TOKEN cannot trigger CI on a pull
// request it opens (GitHub's loop protection), and infra is a required check,
// so a PR opened without it would sit unable to merge until someone nudges it
// by hand (ADR-0021).
//
// Environment: GH_TOKEN, USING_DEFAULT_TOKEN ('true' when no PAT was set),
// RELOCK_BRANCH, GITHUB_REPOSITORY.
import { type Env, type Exec, exec as realExec, isMain, required } from '../lib/actions.ts'

export const BODY =
	'Regenerated by `.github/workflows/terraform-relock.yml` with the real `terraform providers lock`, not Renovate. See `infra/README.md` and issue #118.'

export const DEFAULT_TOKEN_WARNING =
	'::warning::No TRANSLATION_PR_TOKEN is set, so this pull request is opened with the built-in GITHUB_TOKEN and CI will not run on it. Close and reopen it, or push an empty commit, before merging.'

export function main({ env = process.env, exec = realExec, log = console.log }: { env?: Env; exec?: Exec; log?: (line: string) => void } = {}): number {
	const token = required(env, 'GH_TOKEN')
	const branch = required(env, 'RELOCK_BRANCH')
	const repository = required(env, 'GITHUB_REPOSITORY')

	if (env.USING_DEFAULT_TOKEN === 'true') log(DEFAULT_TOKEN_WARNING)

	const git = (...args: string[]) => exec('git', args, { check: true, inherit: true })
	git('config', 'user.name', 'github-actions[bot]')
	git('config', 'user.email', '41898282+github-actions[bot]@users.noreply.github.com')
	// Not through `git()`: a failure message would name the URL, which holds the token.
	const remote = exec('git', ['remote', 'set-url', 'origin', `https://x-access-token:${token}@github.com/${repository}.git`])
	if (remote.status !== 0) throw new Error('git remote set-url origin failed')

	git('switch', '-C', branch)
	git('add', 'infra/.terraform.lock.hcl')
	git('commit', '-m', 'Relock Terraform providers')

	// Force, because the branch is rebuilt from main every run.
	git('push', '--force', 'origin', branch)

	if (exec('gh', ['pr', 'view', branch, '--json', 'number', '--jq', '.number']).status === 0) {
		exec('gh', ['pr', 'edit', branch, '--body', BODY], { check: true, inherit: true })
		log('Updated the open relock pull request.')
	} else {
		exec('gh', ['pr', 'create', '--base', 'main', '--head', branch, '--title', 'Relock Terraform providers', '--body', BODY], {
			check: true,
			inherit: true,
		})
	}
	return 0
}

if (isMain(import.meta.url)) process.exit(main())
